# Generated by Django 2.2.7 on 2022-01-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_temp2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
