# Generated by Django 2.2.7 on 2020-10-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200930_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upravnik',
            options={'verbose_name_plural': 'Upravnici'},
        ),
        migrations.AddField(
            model_name='upravnik',
            name='vrsta',
            field=models.CharField(choices=[('Upravnik - domaće lice', 'Upravnik - domaće lice'), ('Profesionalni upravnik - domaće lice', 'Profesionalni upravnik - domaće lice')], default='Upravnik - domaće lice', max_length=50),
        ),
        migrations.AlterField(
            model_name='upravnik',
            name='ulaz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Ulaz', to='users.Ulaz'),
        ),
    ]
