# Generated by Django 2.2.7 on 2022-01-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_likes', to='home.Post'),
        ),
    ]
