# Generated by Django 2.2.7 on 2020-10-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_upravnik_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ocena_upravnika',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
