# Generated by Django 2.2.7 on 2020-10-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_ocena_upravnika'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ocena_upravnika',
            new_name='oceni_upravnika',
        ),
    ]
