# Generated by Django 2.2.7 on 2020-10-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_prosecna_ocena'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
    ]
