# Generated by Django 2.2.7 on 2020-10-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_komentariupravnika'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KomentariUpravnika',
            new_name='KomentarUpravnika',
        ),
        migrations.AlterModelOptions(
            name='komentarupravnika',
            options={'verbose_name_plural': 'Komentari upravnika'},
        ),
    ]
