# Generated by Django 2.2.7 on 2020-10-02 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201002_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentarupravnika',
            name='upravnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upravnik_ulaza', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='komentarupravnika',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
