# Generated by Django 2.2.7 on 2020-10-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_o_sebi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_organisation',
            field=models.BooleanField(default=False),
        ),
    ]
