# Generated by Django 2.2.7 on 2020-10-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_is_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForUpravnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
