# Generated by Django 2.2.7 on 2020-10-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_messageforupravnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='upravnik',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
