# Generated by Django 2.2.7 on 2020-11-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_upravnik_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upravnik',
            name='firma',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
