# Generated by Django 2.2.7 on 2020-11-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201115_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upravnik_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
