# Generated by Django 2.2.7 on 2020-11-16 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='oceni_upravnika',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
