# Generated by Django 2.2.7 on 2020-11-19 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201116_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secr', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('Grad', models.CharField(blank=True, max_length=50, null=True)),
                ('Opština', models.CharField(blank=True, max_length=50, null=True)),
                ('ulaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Ulaz')),
            ],
        ),
    ]
