# Generated by Django 2.2.7 on 2020-11-30 17:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_temp2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./ /-/_ only.', max_length=150, unique=True, validators=[users.models.MyValidator()], verbose_name='username'),
        ),
    ]
