# Generated by Django 2.2.7 on 2020-11-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201130_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulaz',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
