# Generated by Django 2.2.7 on 2020-12-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20201130_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulaz',
            name='box_full',
            field=models.BooleanField(default=False),
        ),
    ]
