# Generated by Django 2.2.7 on 2020-12-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_ulaz_box_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPapir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Ulaz')),
            ],
        ),
    ]
