# Generated by Django 2.2.7 on 2020-12-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_temppapir'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulaz',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
