# Generated by Django 2.2.7 on 2020-12-05 13:57

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_ulaz_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulaz',
            name='city',
            field=models.CharField(default='Belgrade', max_length=255),
        ),
        migrations.AlterField(
            model_name='ulaz',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='44.79688084502436,20.477120876312256', max_length=63),
        ),
    ]
