# Generated by Django 2.2.7 on 2020-12-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20201205_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppapir',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='temp_papir_photos'),
        ),
    ]
