# Generated by Django 2.2.7 on 2020-12-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_temppapir_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp2',
            name='Broj_stana',
            field=models.IntegerField(null=True),
        ),
    ]
