# Generated by Django 2.2.7 on 2020-12-22 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20201216_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppapir',
            name='ulica_i_broj',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='temppapir',
            name='ulaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Ulaz', unique=True),
        ),
    ]
