# Generated by Django 2.2.7 on 2021-02-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20201223_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='broj_ocenjivaca',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
