# Generated by Django 2.2.7 on 2021-02-20 11:23

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_profile_broj_ocenjivaca'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCepovi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='temp_papir_photos')),
                ('city', models.CharField(default='Belgrade', max_length=60)),
                ('location', location_field.models.plain.PlainLocationField(default='44.79688084502436,20.477120876312256', max_length=63)),
                ('ulaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Ulaz', unique=True)),
            ],
        ),
    ]
