# Generated by Django 2.2.7 on 2021-03-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_tempcepovi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ulaz',
            old_name='box_full',
            new_name='papir_box_full',
        ),
    ]
