# Generated by Django 2.2.7 on 2021-03-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20210303_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulaz',
            name='cep_box_full',
            field=models.BooleanField(default=False),
        ),
    ]
