# Generated by Django 2.2.7 on 2021-03-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_ulaz_cep_box_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulaz',
            name='Grad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ulaz',
            name='Opština',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
