# Generated by Django 2.2.7 on 2021-03-07 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_grad_opština'),
    ]

    operations = [
        migrations.AddField(
            model_name='opština',
            name='Grad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='opštine', to='users.Grad'),
            preserve_default=False,
        ),
    ]
