# Generated by Django 2.2.7 on 2021-03-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210307_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulaz',
            name='Grad',
        ),
        migrations.RemoveField(
            model_name='ulaz',
            name='Opština',
        ),
    ]
