# Generated by Django 2.2.7 on 2021-03-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20210307_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulaz',
            name='Grad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ulazi', to='users.Grad'),
        ),
        migrations.AlterField(
            model_name='ulaz',
            name='Opština',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ulazi', to='users.Opština'),
        ),
    ]
