# Generated by Django 2.2.7 on 2021-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_ulaz_cep_box_filled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcepovi',
            name='cep_box_filled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
