# Generated by Django 2.2.7 on 2021-03-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_tempcepovi_cep_box_filled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcepovi',
            name='cep_box_filled_date',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ulaz',
            name='cep_box_filled_date',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
