# Generated by Django 2.2.7 on 2021-03-28 20:02

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20210314_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulaz',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
