# Generated by Django 2.2.7 on 2021-04-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20210328_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upravnik',
            name='ulaz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upravnik', to='users.Ulaz'),
        ),
    ]
