# Generated by Django 2.2.7 on 2021-05-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20210429_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageforupravnik',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageforupravnik',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
