# Generated by Django 2.2.7 on 2021-06-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20210503_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageForUpravnik',
        ),
    ]
