# Generated by Django 2.2.7 on 2021-12-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_message'),
        ('users', '0056_auto_20211023_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_posts',
            field=models.ManyToManyField(to='home.Post'),
        ),
    ]
