# Generated by Django 2.2.7 on 2021-12-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_customuser_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked_posts',
            field=models.ManyToManyField(related_name='user_likes', to='home.Post'),
        ),
    ]
