# Generated by Django 2.2.7 on 2022-01-06 23:07

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cepovi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Čepovi',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentOfComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Papir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('cena', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Papiri',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Naslov')),
                ('Sadržaj', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('tip', models.CharField(choices=[('Warning', 'Warning'), ('Info', 'Info')], default='Info', max_length=50)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('anketa_id', models.IntegerField(blank=True, null=True)),
                ('anketa_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
