# Generated by Django 2.2.7 on 2020-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_papir'),
    ]

    operations = [
        migrations.AddField(
            model_name='papir',
            name='cena',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
