# Generated by Django 2.2.7 on 2020-10-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_commentofcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commentofcomment',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
