# Generated by Django 2.2.7 on 2020-12-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201130_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='papir',
            name='box_full',
            field=models.BooleanField(default=False),
        ),
    ]
