# Generated by Django 2.2.7 on 2020-12-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_papir_box_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papir',
            name='box_full',
        ),
    ]
