# Generated by Django 2.2.7 on 2020-12-23 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_papir_box_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papir',
            name='cena',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name='papir',
            name='kolicina',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
