# Generated by Django 2.2.7 on 2021-02-20 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_profile_broj_ocenjivaca'),
        ('home', '0017_auto_20201223_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cepovi',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'datum',
                    models.DateTimeField(default=django.utils.timezone.now)
                ),
                (
                    'ulaz',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='users.Ulaz'
                    )
                ),
            ],
        ),
    ]
