# Generated by Django 2.2.7 on 2021-02-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_cepovi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cepovi',
            options={'verbose_name_plural': 'Čepovi'},
        ),
        migrations.AlterModelOptions(
            name='papir',
            options={'verbose_name_plural': 'Papiri'},
        ),
    ]
