# Generated by Django 2.2.7 on 2021-10-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
