# Generated by Django 2.2.7 on 2022-01-06 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(default='Da', max_length=30)),
                ('option_two', models.CharField(default='Ne', max_length=30)),
                ('option_three', models.CharField(blank=True, default='Svejedno', max_length=30)),
                ('ption_one_count', models.IntegerField(default=0)),
                ('ption_two_count', models.IntegerField(default=0)),
                ('ption_three_count', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
