# Generated by Django 2.2.7 on 2020-10-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
