# Generated by Django 2.2.7 on 2020-11-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20201125_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ption_three_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='ption_two_count',
            field=models.IntegerField(default=0),
        ),
    ]
