# Generated by Django 2.2.7 on 2020-11-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20201125_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option_one',
            field=models.CharField(default='Da', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_three',
            field=models.CharField(blank=True, default='Svejedno', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_two',
            field=models.CharField(default='Ne', max_length=30),
        ),
    ]
