# Generated by Django 2.2.7 on 2020-11-30 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20201125_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
