# Generated by Django 2.2.7 on 2021-12-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='num',
            field=models.CharField(max_length=50),
        ),
    ]
