# Generated by Django 2.2.7 on 2021-12-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20211226_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecategory',
            name='icon',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
