# Generated by Django 2.2.7 on 2021-12-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_phonecategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='icon',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='link',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
