# Generated by Django 2.2.7 on 2021-12-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_auto_20211228_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecategory',
            name='numbers',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
